apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-app-1
spec:
  selector:
    matchLabels:
      app: jupyter-1
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyter-1
    spec:
      containers:
      - name: jupyter-1
        image: jupyter/minimal-notebook
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        env:
        - name: JUPYTER_GATEWAY_URL
          value: 'http://192.168.73.129:30050'
        # - name: JUPYTER_GATEWAY_HTTP_USER
          # value: guest
        # - name: JUPYTER_GATEWAY_HTTP_PWD
          # value: guest
        - name: JUPYTER_GATEWAY_VALIDATE_CERT
          value: 'false'
        - name: LOG_LEVEL
          value: DEBUG  
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-http-1
spec:
  ports:
    - port: 8888
      targetPort: 8888
      name: jupyter-notebook-1
      nodePort: 30011
  type: LoadBalancer
  selector:
    app: jupyter-1
