apiVersion: v1
kind: Pod
metadata:
  name: kernel-py
  namespace: enterprise-gateway
  labels:
    kernel_id: kernel-py
    app: enterprise-gateway
    component: kernel
spec:
  restartPolicy: Never
  serviceAccountName: enterprise-gateway-sa
  containers:
  - env:
    - name: EG_RESPONSE_ADDRESS
      value: 192.168.73.130:30050
    - name: KERNEL_LANGUAGE
      value: python
    - name: KERNEL_NAME
      value: kernel-py
    - name: KERNEL_USERNAME
      value: kernel-py
    - name: KERNEL_ID
      value: kernel-py
    - name: KERNEL_NAMESPACE
      value: enterprise-gateway
    image: elyra/kernel-py:dev
    name: kernel-py
    imagePullPolicy: IfNotPresent
